// domain
export const DOMAIN = "http://localhost:3001/student/";
// export const DOMAIN = "https://f32531d8ff9a.ngrok.io";
export const LIMIT = 3;

// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

// types of actions
export const GET_ITEM_REQUEST='GET_ITEM_REQUEST'
export const GET_ITEM_SUCCESS='GET_ITEM_SUCCESS'
export const GET_ITEM_FAILURE='GET_ITEM_FAILURE'
//HAMADD
export const ADD_ITEM_REQUEST='ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS='ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE='ADD_ITEM_FAILURE'

// HAM DELETE
export const DELETE_ITEM_REQUEST='DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS='DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE='DELETE_ITEM_FAILURE'
//HAM UPDATE
export const UPDATE_ITEM_REQUEST='UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS='UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAILURE='UPDATE_ITEM_FAILURE'
//HAM SEARCH
export const SEARCH_ITEM_REQUEST='SEARCH_ITEM_REQUEST'
export const SEARCH_ITEM_SUCCESS='SEARCH_ITEM_SUCCESS'
export const SEARCH_ITEM_FAILURE='SEARCH_ITEM_FAILURE'
//HAM PAGIANTION
export const PAGINATE_ITEM_REQUEST='PAGINATE_ITEM_REQUEST'
export const PAGINATE_ITEM_SUCCESS='PAGINATE_ITEM_SUCCESS'
export const PAGINATE_ITEM_FAILURE='PAGINATE_ITEM_FAILURE'


export const SIGNUP_REQUEST='SIGNUP_REQUEST'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_FAILURE='SIGNUP_FAILURE'

export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

